// Capture poses and effects: running, spin jump, aim up + shot, morph + bomb, missile.
import { open, shot, start, tap } from './samus-lib.mjs';
const { browser, page } = await open('?stage=samus&items=all&room=bomb_room&col=4&row=12');
await start(page);
await page.waitForTimeout(300);
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(250);
await shot(page, 'pose-run');
await page.keyboard.down('KeyZ');
await page.waitForTimeout(200);
await shot(page, 'pose-spin');
await page.keyboard.up('KeyZ');
await page.keyboard.up('ArrowRight');
await page.waitForTimeout(900);
await page.keyboard.down('ArrowUp');
await tap(page, 'KeyX');
await page.waitForTimeout(60);
await shot(page, 'pose-aimup');
await page.keyboard.up('ArrowUp');
await tap(page, 'KeyC');
await tap(page, 'KeyX');
await page.waitForTimeout(120);
await shot(page, 'pose-missile');
await tap(page, 'KeyC');
await tap(page, 'ArrowDown');
await tap(page, 'KeyX');
await page.waitForTimeout(200);
await shot(page, 'pose-ball-bomb');
await page.waitForTimeout(450);
await shot(page, 'pose-bomb-boom');
await browser.close();
